### ISSUE TITLE
第 1 次刷新 TOKEN...上传未成功,重试. 

### ISSUE THREAD

**Issue by imaotai2** [mos9527/bilibili-toolman#19]
第 5 次刷新 TOKEN...
[ 2022-07-22 09:26:23 WebSession WARNING ] 第 5 上传未成功,重试...

貌似不能上传了

**Comment by mos9527** [comment]
cookies登陆上传应该没问题了。但现在的sms登陆加了极验，等把这个弄好再发布新版本

先pull一下看看能不能用吧？

**Comment by imaotai2** [comment]
> cookies登陆上传应该没问题了。但现在的sms登陆加了极验，等把这个弄好再发布新版本
> 
> 先pull一下看看能不能用吧？

一直用的cookie  我看日志能获取到个人账号id 就是上传不成功

我去试试新版本
