### ISSUE TITLE
EditSubmission {'code': 21002, 'message': '此分区暂不可用', 'ttl': 1}

### ISSUE THREAD

**Issue by ixnerd** [mos9527/bilibili-toolman#22]
分区65，网络游戏。
编辑已经开放或者正在审核的稿件均提示：{'code': 21002, 'message': '此分区暂不可用', 'ttl': 1}。

**Comment by mos9527** [comment]
bilibili的[投稿其他规范](https://www.bilibili.com/blackboard/help.html#/?qid=bf07df76411948e6ad63456c458cc37a&pid=7165f587019d441e90baaf7e83f96d08)有说明用户不能更改已经审核稿件的分区
irrc其实正在审核的稿件也无法修改
这应该是b站规定的问题，暂时先close了

**Comment by mos9527** [comment]
了解，等有时间我会尝试修下
感谢指正！
