### ISSUE TITLE
报错：URI 获取失败 - 跳过

### ISSUE THREAD

**Issue by ceiminya** [mos9527/bilibili-toolman#23]
[ 2022-12-29 18:17:20 WebSession   INFO ] 远端结点： https://upos-cs-upcdnqn.bilivideo.com/ugcboss/n221229qn21hrqqrgpqleg3t0vvmbk76.mp4
[ 2022-12-29 18:17:20 WebSession  DEBUG ] 第 1 次刷新 TOKEN...
[ 2022-12-29 18:17:20 WebSession WARNING ] 第 1 上传未成功,重试...
[ 2022-12-29 18:17:21 WebSession   INFO ] 远端结点： https://upos-cs-upcdnqn.bilivideo.com/ugcboss/n221229qn3378cktsy4axrpoz7meec8b.mp4
[ 2022-12-29 18:17:21 WebSession  DEBUG ] 第 2 次刷新 TOKEN...
[ 2022-12-29 18:17:21 WebSession WARNING ] 第 2 上传未成功,重试...
[ 2022-12-29 18:17:23 WebSession   INFO ] 远端结点： https://upos-cs-upcdnqn.bilivideo.com/ugcboss/n221229qn3qxofd37rkd9d11eyz7kbty.mp4
[ 2022-12-29 18:17:23 WebSession  DEBUG ] 第 3 次刷新 TOKEN...
[ 2022-12-29 18:17:23 WebSession WARNING ] 第 3 上传未成功,重试...
[ 2022-12-29 18:17:24 WebSession   INFO ] 远端结点： https://upos-cs-upcdnqn.bilivideo.com/ugcboss/n221229qn2pwg1etqfdauo2u1u9w3ou9.mp4
[ 2022-12-29 18:17:24 WebSession  DEBUG ] 第 4 次刷新 TOKEN...
[ 2022-12-29 18:17:24 WebSession WARNING ] 第 4 上传未成功,重试...
[ 2022-12-29 18:17:25 WebSession   INFO ] 远端结点： https://upos-cs-upcdnqn.bilivideo.com/ugcboss/n221229qn12g2vnbfsn7288c4e2u8lsh.mp4
[ 2022-12-29 18:17:25 WebSession  DEBUG ] 第 5 次刷新 TOKEN...
[ 2022-12-29 18:17:25 WebSession WARNING ] 第 5 上传未成功,重试...
[ 2022-12-29 18:17:26  toolman WARNING ] 上传失败! - 经 5 次重试后仍无法获取 TOKEN - 重试
[ 2022-12-29 18:17:26  toolman  ERROR ] URI 获取失败 - 跳过

**Comment by ceiminya** [comment]
另外用来上传的服务器用短信登录会报错，但本地的就不会，拿两个账号试过了。
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/bilibili_toolman/bilisession/client.py", line 333, in RenewSMSCaptcha
    assert self.login_tokens["captcha_key"]
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/bilibili_toolman/__main__.py", line 6, in <module>
    sys.exit(__main__())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/bilibili_toolman/cli/main.py", line 248, in __main__
    if not setup_session():
  File "/home/ubuntu/.local/lib/python3.10/site-packages/bilibili_toolman/cli/main.py", line 203, in setup_session
    sess.RenewSMSCaptcha(phone)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/bilibili_toolman/bilisession/client.py", line 30, in wrapper
    return _classmethod(self, *a, **k)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/bilibili_toolman/bilisession/common/__init__.py", line 18, in wrapper
    response: Response = classfunc(session, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/bilibili_toolman/bilisession/client.py", line 335, in RenewSMSCaptcha
    raise LoginException(resp, e)
bilibili_toolman.bilisession.common.LoginException: 登陆失败：
<Response 200>:{"code":0,"message":"0","ttl":1,"data":{"is_new":false,"captcha_key":"","recaptcha_url":"https://www.bilibili.com/h5/project-msg-auth/verify?ct=geetest

**Comment by mos9527** [comment]
[报错环节](https://github.com/mos9527/bilibili-toolman/blob/20878cfdc8be6859626fe84edf7d7775738a0877/bilibili_toolman/bilisession/web.py#L383)(i.e. `preupload`)事故率较高，目前原因不明
据信使用新的凭据可减少失败概率，不过除此之外暂时还没有更好的方法
重试次数，延时等参数可在[这里](https://github.com/mos9527/bilibili-toolman/blob/20878cfdc8be6859626fe84edf7d7775738a0877/bilibili_toolman/bilisession/web.py#L66-L71)调节。或许有用？

**Comment by ceiminya** [comment]
> [报错环节](https://github.com/mos9527/bilibili-toolman/blob/20878cfdc8be6859626fe84edf7d7775738a0877/bilibili_toolman/bilisession/web.py#L383)(i.e. `preupload`)事故率较高，目前原因不明
> 
> 据信使用新的凭据可减少失败概率，不过除此之外暂时还没有更好的方法
> 
> 重试次数，延时等参数可在[这里](https://github.com/mos9527/bilibili-toolman/blob/20878cfdc8be6859626fe84edf7d7775738a0877/bilibili_toolman/bilisession/web.py#L66-L71)调节。或许有用？

使用的凭据都刷新过了，重新试了一下，本地和香港的机子都能上传，台湾的就一直不行，但我机子配置的环境都是一样的，所以可能是网络的问题？包括手机登录获取凭据也是出现一样的情况。
