### ISSUE TITLE
如何把投稿格式改为自制

### ISSUE THREAD

**Issue by qimuwen** [mos9527/bilibili-toolman#27]
我想用这个项目来投稿我我自制的视频，我该怎么把投稿格式改为自制

**Comment by mos9527** [comment]
加入 `--original` 选项
如果是用action的话：
![image](https://github.com/mos9527/bilibili-toolman/assets/31397301/2932fbdc-c8a5-4c1c-ade2-2318a1f94445)

**Comment by qimuwen** [comment]
> 加入 选项 如果是用action的话：`--original` ![图像](https://user-images.githubusercontent.com/31397301/245195810-2932fbdc-c8a5-4c1c-ade2-2318a1f94445.png)

我是用的是web，python代码用的是样例，不知道怎么改

**Comment by mos9527** [comment]
在样例中
```python
...
# 添加视频 (P)，注意仅父节点（稿件）描述会被显示；分 P 视频和父稿件同类型
>>> cover = session.UploadCover('封面测试.png')
>>> submission.cover_url = cover['data']['url']
```
此出不同于样例：
```python
# submission.source 不需要设置
# 设置原创即调节 copyright 属性
>>> submission.copyright = Submission.COPYRIGHT_ORIGINAL 
# 设置不允许转载即调节 no_reprint 属性
>>> submission.no_reprint = Submission.REPRINT_DISALLOWED 
```

**Comment by qimuwen** [comment]
谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月13日 18:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [mos9527/bilibili-toolman] 如何把投稿格式改为自制 (Issue #27) |

在样例中

...
# 添加视频 (P)，注意仅父节点（稿件）描述会被显示；分 P 视频和父稿件同类型>>>cover=session.UploadCover('封面测试.png')
>>>submission.cover_url=cover['data']['url']

此出不同于样例：

# submission.source 不需要设置# 设置原创即调节 copyright 属性>>>submission.copyright=Submission.COPYRIGHT_ORIGINAL# 设置不允许转载即调节 no_reprint 属性>>>submission.no_reprint=Submission.REPRINT_DISALLOWED

**Comment by qimuwen** [comment]
还有一个问题，如何使稿件参假B站的话题活动，我尝试在tag里添加：#话题#、#话题都是纯文本的tag

**Comment by mos9527** [comment]
[看看这个？](https://github.com/mos9527/bilibili-toolman/commit/6780928e3042da3cf080d213f6e20b9e7f60477b)
