### ISSUE TITLE
上传视频验证码限制

### ISSUE THREAD

**Issue by HowHsu** [mos9527/bilibili-toolman#30]
请问使用本库上传视频会触发验证码吗，我现在用的另一个库，上传到9个左右时候返回错误，提示需要输入验证码。似乎B站一天内只能投稿9个左右，之后的投稿会要求验证码

**Comment by mos9527** [comment]
[考虑使用 上传助手API 进行投稿](https://github.com/mos9527/bilibili-toolman#%E5%87%86%E5%A4%87%E5%87%AD%E6%8D%AE) 
未经测试。但就使用经验，不论日投稿量，该途径投貌似不会触发人机校验
